# -*- coding: utf-8 -*-

'''
This script is created for generating "char_table.h" and character
images for the layout archive. 
'''

import codecs
import datetime

import fire
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("SourceHanSansCN-Bold.otf", 19)
Suffixs = ['a', 'A_us', 
           'B', 'C', 'D', 
           'e', 'E_us', 
           'F', 'G', 
           'H', 'ha', 'he', 'ho', 
           'i', 'I_us',
           'J', 
           'ka', 'ke', 'ki', 'ko', 'ku', 
           'M', 'ma', 'mi', 'mo', 
           'N', 'no', 
           'o', 'O_us', 
           'R', 'ra', 'ro', 'ru',
           'S', 'sa', 'se', 'si', 'su',
           'T', 'ta', 'ti', 'to', 'tu',
           'u', 'U_us',
           'Y', 'ya', 'yo', 'yu']

def DrawChar(char):
    image = Image.new('RGBA', (20,20), color=0xFFFFFF)
    draw = ImageDraw.Draw(image)
    draw.text((0,0), char, font=font)
    return image

def DrawAll(path):
    s = codecs.open(path, 'r', 'utf-8-sig').read().replace('\n', '').replace('\r', '')
    if len(s) > len(Suffixs):
        raise ValueError("Input charset is too long!")
    
    charTable = []

    for i in range(len(Suffixs)):
        c = ' '
        if i < len(s):
            c = s[i]
        image = DrawChar(c)
        path = 'Lyt/timg/Txt_%s.png'%(Suffixs[i])
        print 'Save:', path
        image.save(path)

        charTable.append("{L'%s'"%c+', "%s"}, '%Suffixs[i])
        if (len(charTable)+1) % 6 == 0:
            charTable.append('\n\t')
    
    timestr = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    charTable = '''// This file is auto generated by gen_char_table.py
// %s
#include "def.h"

CharTableEntry const charTable[] =
{
\t%s
};'''%(timestr, ''.join(charTable))

    codecs.open('char_table.h', 'w', 'utf-8').write(charTable)

if __name__ == '__main__':
    fire.Fire()
